"""
build.py — EyeTyper Build Script
Uses your existing spec files from specs/ folder.

Usage (from project ROOT):
    python build.py              # auto-detects platform
    python build.py --platform win
    python build.py --platform linux
    python build.py --platform mac

Expected project layout:
    ROOT/
    ├── build.py
    ├── main.py
    ├── calibrator.py
    ├── rthook_cwd.py
    ├── icon.ico
    ├── icon2.ico
    ├── calibrator_icon.ico
    ├── data/
    │   └── face_landmarker.task
    ├── debug/
    │   └── debug_gaze.py
    ├── specs/
    │   ├── EyeTyper-windows.spec
    │   ├── EyeTyper-Calibrator-windows.spec
    │   ├── EyeTyper-linux.spec
    │   ├── EyeTyper-Calibrator-linux.spec
    │   ├── EyeTyper-mac.spec
    │   └── EyeTyper-Calibrator-mac.spec
    └── app/
        └── ...

Output:
    dist/EyeTyper/
      (Windows) EyeTyper.exe + EyeTyperCalibrator.exe + EyeTyper_Debug.exe + _internal/
      (Linux)   EyeTyper    + EyeTyperCalibrator    + EyeTyper_Debug    + _internal/
      (macOS)   EyeTyper.app + EyeTyperCalibrator.app
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
import sysconfig

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT         = os.path.dirname(os.path.abspath(__file__))
SPECS_DIR    = os.path.join(ROOT, "specs")
MODEL_PATH   = os.path.join(ROOT, "data", "face_landmarker.task")
DEBUG_SCRIPT = os.path.join(ROOT, "debug", "debug_gaze.py")
RTHOOK       = os.path.join(ROOT, "rthook_cwd.py")
SITE         = sysconfig.get_path("purelib")

# ── Debug spec (generated at build time, not stored on disk) ──────────────────
# The debug tool is a plain OpenCV script — no PySide6, no firebase, no spellcheck.
# We generate a minimal spec for it so it stays fast and small.

DEBUG_SPEC = """\
# Auto-generated by build.py — debug build
import os, glob, sysconfig
SITE = sysconfig.get_path("purelib")

def _bins(pkg):
    out = []
    base = os.path.join(SITE, pkg)
    if not os.path.exists(base):
        return out
    for ext in ("*.dll", "*.pyd", "*.so"):
        for f in glob.glob(os.path.join(base, "**", ext), recursive=True):
            out.append((f, os.path.relpath(os.path.dirname(f), SITE)))
    return out

a = Analysis(
    [{script!r}],
    pathex=[{root!r}],
    binaries=_bins("mediapipe") + _bins("cv2"),
    datas=[
        ({model!r}, "data"),
    ],
    hiddenimports=[
        "mediapipe", "mediapipe.tasks", "mediapipe.tasks.python",
        "mediapipe.tasks.python.vision", "mediapipe.python",
        "mediapipe.python.solutions",
        "matplotlib", "matplotlib.pyplot", "matplotlib.backends",
        "matplotlib.backends.backend_agg",
        "cv2", "numpy", "openpyxl", "openpyxl.styles", "openpyxl.utils",
    ],
    hookspath=[],
    runtime_hooks=[{rthook}],
    excludes=["tkinter", "scipy", "pandas",
              "PySide6", "IPython", "jupyter", "firebase_admin"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="EyeTyper_Debug",
    debug=False, strip={strip}, upx={upx},
    upx_exclude={upx_exclude!r},
    console=True,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip={strip}, upx={upx},
    upx_exclude={upx_exclude!r},
    name="EyeTyper_Debug",
)
"""

# ── Per-platform build table ───────────────────────────────────────────────────

BUILDS = {
    "win": [
        {
            "label":      "EyeTyper (main)",
            "spec_file":  "EyeTyper-windows.spec",
            "dist_name":  "EyeTyper",
            "is_debug":   False,
        },
        {
            "label":      "EyeTyper Calibrator",
            "spec_file":  "EyeTyper-Calibrator-windows.spec",
            "dist_name":  "EyeTyperCalibrator",
            "is_debug":   False,
        },
        {
            "label":      "EyeTyper Debug",
            "spec_file":  None,          # generated inline
            "dist_name":  "EyeTyper_Debug",
            "is_debug":   True,
        },
    ],
    "linux": [
        {
            "label":      "EyeTyper (main)",
            "spec_file":  "EyeTyper-linux.spec",
            "dist_name":  "EyeTyper",
            "is_debug":   False,
        },
        {
            "label":      "EyeTyper Calibrator",
            "spec_file":  "EyeTyper-Calibrator-linux.spec",
            "dist_name":  "EyeTyperCalibrator",
            "is_debug":   False,
        },
        {
            "label":      "EyeTyper Debug",
            "spec_file":  None,
            "dist_name":  "EyeTyper_Debug",
            "is_debug":   True,
        },
    ],
    "mac": [
        {
            "label":      "EyeTyper (main)",
            "spec_file":  "EyeTyper-mac.spec",
            "dist_name":  "EyeTyper",
            "is_debug":   False,
        },
        {
            "label":      "EyeTyper Calibrator",
            "spec_file":  "EyeTyper-Calibrator-mac.spec",
            "dist_name":  "EyeTyperCalibrator",
            "is_debug":   False,
        },
        # No debug build on macOS — just run: python debug/debug_gaze.py
    ],
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def detect_platform() -> str:
    s = platform.system().lower()
    if s == "windows": return "win"
    if s == "darwin":  return "mac"
    return "linux"


def banner(text: str) -> None:
    print(f"\n{'='*60}\n  {text}\n{'='*60}")


def check_prerequisites(plat: str) -> None:
    banner("Checking prerequisites")

    errors = []

    if not os.path.exists(MODEL_PATH):
        errors.append(
            f"  [MISS] data/face_landmarker.task\n"
            f"         Download: curl -o data\\face_landmarker.task https://storage.googleapis.com/"
            f"mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task"
        )
    else:
        print(f"  [OK]   data/face_landmarker.task")

    if not os.path.exists(DEBUG_SCRIPT):
        errors.append(f"  [MISS] debug/debug_gaze.py")
    else:
        print(f"  [OK]   debug/debug_gaze.py")

    if not os.path.exists(RTHOOK):
        errors.append(
            f"  [MISS] rthook_cwd.py\n"
            f"         Create it with:  echo \"import os, sys; os.chdir(sys._MEIPASS)\" > rthook_cwd.py"
        )
    else:
        print(f"  [OK]   rthook_cwd.py")

    # Check spec files exist
    for build in BUILDS[plat]:
        sf = build["spec_file"]
        if sf is None:
            continue
        path = os.path.join(SPECS_DIR, sf)
        if not os.path.exists(path):
            errors.append(f"  [MISS] specs/{sf}")
        else:
            print(f"  [OK]   specs/{sf}")

    # Check PyInstaller
    try:
        import PyInstaller
        print(f"  [OK]   PyInstaller {PyInstaller.__version__}")
    except ImportError:
        errors.append("  [MISS] PyInstaller — run: pip install pyinstaller")

    if errors:
        print("\n[ERRORS FOUND]\n")
        for e in errors:
            print(e)
        sys.exit(1)

    print("\n  All prerequisites satisfied.")


def write_debug_spec(plat: str) -> str:
    """Write the auto-generated debug .spec to specs/ and return its path."""
    is_mac   = plat == "mac"
    is_linux = plat == "linux"

    rthook_val = repr(RTHOOK) if os.path.exists(RTHOOK) else "[]"
    # On mac: no upx; on linux: strip=True; on win: standard
    strip      = "True"  if is_linux else "False"
    upx        = "False" if is_mac   else "True"
    upx_exclude = ["vcruntime140.dll", "python312.dll",
                   "Qt6Core.dll", "Qt6Widgets.dll", "Qt6Gui.dll"]

    spec_content = DEBUG_SPEC.format(
        script      = DEBUG_SCRIPT,
        root        = ROOT,
        model       = MODEL_PATH,
        rthook      = rthook_val,
        strip       = strip,
        upx         = upx,
        upx_exclude = upx_exclude,
    )

    spec_path = os.path.join(SPECS_DIR, "EyeTyper-Debug-generated.spec")
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    print(f"  [OK]   Debug spec written -> specs/EyeTyper-Debug-generated.spec")
    return spec_path


def run_pyinstaller(spec_path: str, label: str) -> None:
    print(f"\n{'-'*60}")
    print(f"  Building: {label}")
    print(f"  Spec:     {os.path.relpath(spec_path, ROOT)}")
    print(f"{'-'*60}")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--distpath", os.path.join(ROOT, "dist"),
        "--workpath", os.path.join(ROOT, "build_tmp"),
        spec_path,
    ]

    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        print(f"\n[ERROR] Build failed for: {label}")
        print("  Check the PyInstaller output above for details.")
        sys.exit(1)

    print(f"[OK]  {label} built successfully.")


def _safe_move_file(src: str, dest: str) -> None:
    """
    Move a single file reliably on Windows and POSIX.

    shutil.move() tries os.rename() first; on Windows that can raise
    FileNotFoundError when the destination directory was freshly created
    (directory entry not yet flushed).  copy2 + unlink is always safe.
    """
    try:
        os.rename(src, dest)
    except OSError:
        shutil.copy2(src, dest)
        os.remove(src)


def merge_into_one_folder(plat: str) -> str:
    """
    Merge dist/<n>/ folders produced by each spec into dist/EyeTyper/.
    Shared libraries (_internal/) are deduplicated automatically.

    FIX: first BUILDS entry has dist_name="EyeTyper" == out_dir, so
    iterating os.listdir while writing into the same dir corrupts the
    snapshot on Windows.  Skip the self-merge with a normalised path check.
    """
    out_dir = os.path.join(ROOT, "dist", "EyeTyper")
    os.makedirs(out_dir, exist_ok=True)
    out_dir_norm = os.path.normcase(os.path.abspath(out_dir))

    for build in BUILDS[plat]:
        dist_name = build["dist_name"]
        src_dir   = os.path.join(ROOT, "dist", dist_name)

        if os.path.normcase(os.path.abspath(src_dir)) == out_dir_norm:
            print(f"  Skipping self (already in place): dist/{dist_name}/")
            continue

        if not os.path.exists(src_dir):
            print(f"  [WARN] Expected folder missing, skipping: dist/{dist_name}")
            continue

        print(f"  Merging dist/{dist_name}/ -> dist/EyeTyper/")

        for item in os.listdir(src_dir):
            src  = os.path.join(src_dir, item)
            dest = os.path.join(out_dir, item)

            if os.path.isdir(src):
                if os.path.exists(dest):
                    _merge_dirs(src, dest)
                else:
                    shutil.move(src, dest)
            else:
                if not os.path.exists(dest):
                    _safe_move_file(src, dest)

        shutil.rmtree(src_dir, ignore_errors=True)

    return out_dir


def _merge_dirs(src: str, dest: str) -> None:
    """Recursively copy src into dest, skipping files that already exist."""
    for item in os.listdir(src):
        s = os.path.join(src, item)
        d = os.path.join(dest, item)
        if os.path.isdir(s):
            if os.path.exists(d):
                _merge_dirs(s, d)
            else:
                shutil.move(s, d)
        else:
            if not os.path.exists(d):
                _safe_move_file(s, d)


def cleanup(plat: str) -> None:
    # Remove temp build workspace
    shutil.rmtree(os.path.join(ROOT, "build_tmp"), ignore_errors=True)

    # Remove generated debug spec
    generated = os.path.join(SPECS_DIR, "EyeTyper-Debug-generated.spec")
    if os.path.exists(generated):
        os.remove(generated)

    print("[OK]  Temporary build files removed.")


def print_summary(out_dir: str, plat: str) -> None:
    banner("Build Complete 🎉")
    print(f"  Output folder:\n    {out_dir}\n")

    if os.path.exists(out_dir):
        items = sorted(os.listdir(out_dir))
        for item in items:
            full = os.path.join(out_dir, item)
            if os.path.isfile(full):
                size_kb = os.path.getsize(full) / 1024
                print(f"    [OK]  {item:<40} ({size_kb:.0f} KB)")
            elif os.path.isdir(full):
                dir_size = sum(
                    os.path.getsize(os.path.join(dp, f))
                    for dp, _, files in os.walk(full)
                    for f in files
                ) / (1024 * 1024)
                print(f"    [DIR] {item:<40} ({dir_size:.1f} MB)")

    print()
    if plat == "win":
        print("  [WARNING] Share the ENTIRE dist\\EyeTyper\\ folder.")
        print("     The .exe files need _internal\\ to run -- do NOT share just the .exe.")
    elif plat == "linux":
        print("  [WARNING] Share the ENTIRE dist/EyeTyper/ folder.")
        print("     Binaries need _internal/ to run.")
    else:
        print("  [WARNING] Share the .app bundles directly.")
        print("     Users can drag them to /Applications.")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="EyeTyper build script")
    parser.add_argument(
        "--platform", choices=["win", "linux", "mac"],
        default=None,
        help="Target platform (default: auto-detect)"
    )
    args = parser.parse_args()

    plat = args.platform or detect_platform()

    banner(f"EyeTyper — Build Script  [{plat.upper()}]")
    print(f"  Project root : {ROOT}")
    print(f"  Python       : {sys.version.split()[0]}")
    print(f"  Platform     : {plat}")

    check_prerequisites(plat)

    # Write generated debug spec if needed
    for build in BUILDS[plat]:
        if build["is_debug"]:
            spec_path = write_debug_spec(plat)
            build["_generated_spec"] = spec_path

    # Run PyInstaller for each app
    banner("Building executables")
    for build in BUILDS[plat]:
        if build["is_debug"]:
            spec_path = build["_generated_spec"]
        else:
            spec_path = os.path.join(SPECS_DIR, build["spec_file"])

        run_pyinstaller(spec_path, build["label"])

    # Merge all dist/<name>/ folders into dist/EyeTyper/
    banner("Merging into single folder")
    out_dir = merge_into_one_folder(plat)

    # Clean up build_tmp and generated spec
    banner("Cleaning up")
    cleanup(plat)

    print_summary(out_dir, plat)


if __name__ == "__main__":
    main()